# Generated by Django 5.1 on 2025-08-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
    ]
