# Generated by Django 5.1 on 2025-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_auto_20250809_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.URLField(),
        ),
    ]
