# Generated by Django 5.1 on 2025-09-06 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='goal',
            new_name='goal_amount',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 6, 4, 47, 56, 156603, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 6, 4, 48, 11, 206948, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 6, 4, 48, 26, 935833, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
