# Generated by Django 5.1 on 2025-08-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='commment',
            new_name='comment',
        ),
    ]
